admin:
  existingSecret: admin-secret

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-operator-kube-p-prometheus.prometheus-operator:9090
     access: proxy
     isDefault: true

dashboards:
  default:
    prometheus-stats:
      # Ref: https://grafana.com/dashboards/2
      gnetId: 2
      revision: 2
      datasource: Prometheus
