apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds/*.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 33.0.0
  releaseName: prometheus-operator
  namespace: prometheus-operator
  valuesFile: values.yaml
  includeCRDs: false
