apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds/crd-servicemonitors.yaml
- crds/crd-prometheuses.yaml
- crds/crd-alertmanagers.yaml
- crds/crd-podmonitors.yaml
- crds/crd-prometheusrules.yaml
- crds/crd-thanosrulers.yaml
- crds/crd-alertmanagerconfigs.yaml
- crds/crd-probes.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 33.0.0
  releaseName: prometheus-operator
  namespace: prometheus-operator
  valuesFile: values.yaml
  includeCRDs: false
